---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lenovo.
--- DateTime: 2023/7/24 11:11
---

if true then
    print('hello')
end

local function say(status)
    if (status == 0) then
        print('hello world')
    else
        print('hello lua')
    end
end

say(0)
say(1)


-- 多if else
local status = 1;

if (status == 0) then
    print('hello 1');
elseif (status == 1) then
    print('hello 2');
else
    print('hello 3');
end