---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lenovo.
--- DateTime: 2023/7/21 13:09
---

--while (true)
--    do
--    print("循环执行")
--end

local func = require "com.bigshen.learningDemo.lua.fuction";

local a=1
repeat
    print(a)
    a=a+1
until (a>20)
for i = 1,10 do
    print(i)
end


table={key1="123",key2="345"}
for k,v in pairs(table) do
    print(k,v)
end
local b=2
func.myPrint(a)
func.add(a,b)