---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lenovo.
--- DateTime: 2023/7/21 13:17
---


--function max (num1,num2)
--    if (num1 > num2) then
--        result = num1
--    else
--        result = num2
--    end
--
--    return result
--end
--
---- 调用函数
--print("两值比较最大值为 ",max(10,4))
--print("两值比较最大值为 ",max(5,6))

local _M = {}

function _M.myPrint(param)
    print("这是打印函数 -   ##",param,"##")
end

function _M.add(num1,num2)
    result = num1 + num2
    -- 调用传递的函数参数
    _M.myPrint(result)
end
_M.myPrint(10)
-- myprint 函数作为参数传递
_M.add(2,5)




function maximum (a)
    local mi = 1             -- 最大值索引
    local m = a[mi]          -- 最大值
    for i,val in ipairs(a) do
        if val > m then
            mi = i
            m = val
        end
    end
    return m, mi
end

print(maximum({8,10,23,12,5}))

return _M