#CRL Configuration

## crl type eg: HTTP、LDAP、FILE
TYPE = "{{TYPE}}";

## crl name
CRL_NAME = "{{CRL_NAME}}";

## crl desc
DESC = "{{DESC}}";

## crl timeout
TIMEOUT = {{TIMEOUT}};

## crl url eg："http://ip:port/path/file"
URL = "{{URL}}";

## ldap username
LDAP_USERNAME = "{{LDAP_USERNAME}}";

## ldap password
LDAP_PASSWORD = "{{LDAP_PASSWORD}}";

## ldap Search Base
LDAP_SEARCH_PATH = "{{LDAP_SEARCH_PATH}}";

## ldap condition
LDAP_CONDITION = "{{LDAP_CONDITION}}";

## ldap attr
LDAP_ATTRIBUTION = "{{LDAP_ATTRIBUTION}}";

## output dir eg：/kssl/CRL/crl/http
OUTPUT_DIR = "{{OUTPUT_DIR}}";