server:
  port: 28080
  additional-port: 28081
  additional-address: 0.0.0.0

spring:
  redis:
    host: localhost
    port: 6379
    password: ENC(xvbQ57E/87qvbbmNI8A1OKZGVIISBy/X0yWTYb3YVfSt0FtRGZ+pp+XpfdMra6dP)
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）默认 8。根据 CPU 核心数调整，通常为 CPU * 2 + 2
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1。5000~60000（避免线程长时间阻塞）
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8。CPU * 2
        max-idle: 8
        # 连接池中的最大空闲连接 默认 8。0 或 1（低负载场景）
        min-idle: 0
        # 每 timeBetweenEvictionRunsMillis 毫秒秒清理连接池中空闲的连接 (默认-1,不开启) 1000~60000（根据负载调整）
        timeBetweenEvictionRuns: 30000
        # 在borrow一个redis实例时，是否提前进行vaidate操作；如果为true，则得到的redis实例均是可用的 (默认false)
        testOnBorrow: true
        # 如果为true，表示有一个idle object evitor线程对idle object进行扫描，如果validate失败，此object会被从pool中drop掉(默认false)
        testWhileIdle: true

jasypt:
  encryptor:
    # 使用自定义加密器
    bean: codeSheepEncryptorBean
    # 安全考虑，加密密钥不要写在配置中 java -jar xx.jar --jasypt.encryptor.password=CodeSheep
    # java -Djasypt.encryptor.password=CodeSheep -jar xx.jar
    password: CodeSheep

rocketmq:
  enhance:
    # 启动隔离，用于激活配置类EnvironmentIsolationConfig
    # 启动后会自动在topic上拼接激活的配置文件，达到自动隔离的效果
    enabledIsolation: true
    # 隔离环境名称，拼接到topic后，topic_dev，默认空字符串
    environment: dev
  name-server: 192.168.1.224:9876 # 访问地址
  consumer:
    group: springboot_consumer_group
      # 一次拉取消息最大值，注意是拉取消息的最大值而非消费最大值
    pull-batch-size: 10
  producer:
    group: Pro_Group  # 生产者组
    sendMessageTimeout: 3000 # 消息发送超时时长，默认3s
    retryTimesWhenSendFailed: 3 # 同步发送消息失败重试次数，默认2
    retryTimesWhenSendAsyncFailed: 3 # 异步发送消息失败重试次数，默认2
    # 消息最大长度，默认1024 * 1024 * 4(默认4M)
    maxMessageSize: 4096
    # 压缩消息阈值，默认4k(1024 * 4)
    compressMessageBodyThreshold: 4096
    # 是否在内部发送失败时重试另一个broker，默认false
    retryNextServer: false

jwt:
  enabled: true

